export enum Category {
  utilities = 'Utilities',
  food = 'Food',
  Transportation = 'Transportation',
  healthcare = 'Healthcare',
  insurance = 'Insurance',
  personal = 'Personal',
  spending = 'Spending',
  savings = 'Savings',
  education = 'Education',
  donation = 'Donation',
  gifts = 'Gifts',
  childcare = 'Childcare',
  travel = 'Travel',
  subscription = 'Substriction',
  loan = 'Loan',
}
