name: Prettier

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Check formatting
        run: npx prettier --check .
